### ISSUE TITLE
Dropdown not working

### ISSUE THREAD

**Issue by bhavindholakiya** [puikinsh/CoolAdmin#10]
I integrated CoolAdmin theme in my Angular project but the dropdown menu not working even I install all the .js file including jQuery.js and Bootstrap.js.

I confirmed that all these js files are loading properly.

Please help me.

**Comment by harshnagarkar** [comment]
Which dropdown menu are we talking about? @bhavindholakiya

**Comment by bhavindholakiya** [comment]
@harshnagarkar I'm talking about profile menu dropdown which placed at top-right corner in navbar. and all other select2 dropdown.

**Comment by harshnagarkar** [comment]
Alright, l will try to replicate and see whats the issue.

**Comment by srehmanali** [comment]
Hi, since this question is related to select2 so I want share the dropdown issue I'm facing. I implemented this template to asp.net mvc but the select2 dropdown is not working though I just copy paste the exact code. on screen it shows the 2 dropdowns please see the image url and the error message is:

> select2.min.js:2 Uncaught TypeError: Cannot read property 'top' of undefined
>     at d.c._positionDropdown (select2.min.js:2)
>     at d.j [as _positionDropdown] (select2.min.js:1)
>     at d.c._showDropdown (select2.min.js:2)
>     at d.j [as _showDropdown] (select2.min.js:1)
>     at e.<anonymous> (select2.min.js:2)
>     at e.d.invoke (select2.min.js:1)
>     at e.d.trigger (select2.min.js:1)
>     at e.trigger (select2.min.js:2)
>     at e.<anonymous> (select2.min.js:2)
>     at e.d.invoke (select2.min.js:1)

[https://www.screencast.com/t/pwbdxHSRD8](url)
